config:
  auto-restart: false
  auto-download: true
  auto-update: true
  jenkins-url: http://88.151.197.136:8081
  jenkins-username: admin
  jenkins-password: admin
  jenkins-jobs:
    test:
      job-name: Test
      job-artifact: Test.jar
      last-successful-build-number: null